-- create user demo1

CREATE USER DEMO1 identified by 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK ;

-- ROLES
ALTER USER DEMO1 DEFAULT ROLE CONNECT,RESOURCE;

-- SYSTEM PRIVILEGES
GRANT EXECUTE ON SYS.XMLTYPE TO DEMO1;
